# Generated by Django 4.2.28 on 2026-02-07 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('generic_name', models.CharField(blank=True, max_length=150, null=True)),
                ('dosage', models.CharField(max_length=50)),
                ('form', models.CharField(choices=[('comprime', 'Comprimé'), ('gelule', 'Gélule'), ('sirop', 'Sirop'), ('injectable', 'Injectable'), ('pommade', 'Pommade'), ('suspension', 'Suspension')], max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_stock_level', models.PositiveIntegerField(default=10)),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.product')),
            ],
            options={
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
    ]
