# Generated by Django 4.2.28 on 2026-02-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('BLOCKED', 'Vente bloquée'), ('SUCCESS', 'Vente réussie')], max_length=20)),
                ('reason', models.CharField(choices=[('EXPIRED_BATCH', 'Lots expirés'), ('INSUFFICIENT_STOCK', 'Stock insuffisant'), ('UNAUTHORIZED_PRODUCT', 'Produit non autorisé'), ('OTHER', 'Autre')], max_length=30)),
                ('requested_quantity', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_audits', to='core.pharmacy')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedSaleAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('expired_batch', 'Lot expiré'), ('insufficient_stock', 'Stock insuffisant'), ('product_inactive', 'Produit inactif')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pharmacy')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
