# Generated by Django 4.2.28 on 2026-02-09 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_saleauditlog_blockedsaleaudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit vente', 'verbose_name_plural': 'Audits ventes'},
        ),
        migrations.AlterField(
            model_name='saleauditlog',
            name='action',
            field=models.CharField(choices=[('SUCCESS', 'Vente réussie'), ('BLOCKED', 'Vente bloquée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saleauditlog',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_audit_logs', to='core.pharmacy'),
        ),
        migrations.AlterField(
            model_name='saleauditlog',
            name='reason',
            field=models.CharField(choices=[('expired_stock', 'Stock expiré'), ('insufficient_stock', 'Stock insuffisant'), ('unauthorized_product', 'Produit non autorisé'), ('inactive_product', 'Produit inactif'), ('other', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='saleauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BlockedSaleAudit',
        ),
    ]
