# Generated by Django 4.2.28 on 2026-02-14 11:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stockentryauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBatchConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockentryauditlog',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='stockentryauditlog',
            name='stock_entry',
        ),
        migrations.RemoveField(
            model_name='stockentryauditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='requires_prescription',
        ),
        migrations.AddField(
            model_name='productbatch',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='StockEntryAudit',
        ),
        migrations.DeleteModel(
            name='StockEntryAuditLog',
        ),
        migrations.AddField(
            model_name='salebatchconsumption',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productbatch'),
        ),
        migrations.AddField(
            model_name='salebatchconsumption',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_consumptions', to='core.sale'),
        ),
    ]
