# Generated by Django 4.2.28 on 2026-02-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_salebatchconsumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
