# Generated by Django 4.2.28 on 2026-02-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pharmacy_current_period_end_pharmacy_grace_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
