# Generated by Django 4.2.28 on 2026-02-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pharmacy_country_pharmacy_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
