# Generated by Django 4.2.28 on 2026-02-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_pharmacy_country_code_alter_pharmacy_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='country',
            field=models.CharField(default='Chad', max_length=100),
        ),
    ]
